language: python
python:
  - "3.6"
  - "3.7-dev"  # 3.7 development branch
# command to install dependencies
install:
  - install graphviz
  - pip install -U-r requirements.txt
  - pip install .
# command to run tests
script:
  - pytest -vvv tests
